# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c94abf85c02e1fa879491c3aba72e30104d01ce6557e16427bdabf82348638287cefaf15817c28bf4e875b4f238750b7d4c24775bb4c522651354eb2e51a91a7

test:
  secret_key_base: d8a9d4f00dfde5fc8697345e04ec1f4d99973fa88e2b0e5b380e0fb11f6e888b71c4b9499d8279452e3c6a38bde3c26a8ec9cdd3d54b9e3d0f243c95573624f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
